apiVersion: apps/v1
kind: Deployment
metadata:
 name: simple-webpage-deployment
 labels:
   app: simple-webpage
spec:
 replicas: 3
 selector:
   matchLabels:
     app: simple-webpage
 template:
   metadata:
     labels:
       app: simple-webpage
   spec:
     containers:
     - name: simple-webpage
       image: pt1212/cicd:5
       ports:
       - containerPort: 90
 strategy:
   type: RollingUpdate
   rollingUpdate:
     maxUnavailable: 1
